### ISSUE TITLE
Battery Warning Despite Battery Having 100%

### ISSUE THREAD

**Issue by muellert** [streetturtle/awesome-wm-widgets#75] opened 2019-03-21 14:14 UTC
I get spurious battery warnings when the battery is 100% full and I am on mains power. The battery arc is hollow, since my laptop stops charging when the battery is full and it runs on mains. When I put the mouse over the circle, it shows a small popup saying that the battery is 100% full. I would like to receive those battery warnings only if the battery is actually weak.

I am running 94252c405a87208b859c1ff47e7e2f30f32a1411 with Awesome 4.2 on Debian/Buster (shouldn't matter, imho).

**Comment by streetturtle** [comment] 2019-03-21 14:16
That's strange. Can you run ’acpi -i’ in terminal when it happens and paste it here.

**Comment by muellert** [comment] 2019-03-21 14:37
$ acpi -i
Battery 0: Full, 100%
Battery 0: design capacity 8508 mAh, last full capacity 7484 mAh = 87%
$

**Comment by streetturtle** [comment] 2019-03-24 02:34
I just merged a small refactoring PR in battery-arc, could you please try again on latest master.

**Comment by muellert** [comment] 2019-03-24 19:29
Hi streetturtle!
I have pulled your code and run it at the moment, but this code has an even worse problem than before: Now, the battery fill is always displayed at 100% (ie, no charching required), when I can see with the mouse-over and also from the command line, that it is half empty already.

![battery-indicator-wrong](https://user-images.githubusercontent.com/1183079/54884613-13132600-4e6b-11e9-8849-8242a5935b6c.png)

**Comment by muellert** [comment] 2019-03-25 11:14
Hi! Today, I've re-done the experiment and had the battery run down a bit more. 
![battery-indicator-way-off](https://user-images.githubusercontent.com/1183079/54915493-2c5db600-4eef-11e9-9091-59a9d129227f.png)

**Comment by streetturtle** [comment] 2019-03-28 18:26
As I cannot reproduce your issue, I would  "print" (by showing notification with calculated value) the calculated value, I would start on this line https://github.com/streetturtle/awesome-wm-widgets/blob/master/batteryarc-widget/batteryarc.lua#L102 with this notification:  `naughty.notify{text = tostring(charge_cap)}`.

**Comment by streetturtle** [comment] 2019-03-29 21:43
So I reverted the latest commit.... Could you please try again?

**Closed** 2020-01-14 13:54 UTC

**Comment by hi-im-buggy** [comment] 2020-09-24 10:32
Could you reopen this issue? I'm having the exact same problem again on my laptop. Output of `uname -a`:
```
Linux spasus 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
```

**Comment by hi-im-buggy** [comment] 2020-09-24 10:40
I'm facing the same issue on my laptop when it's at 100% and charging, but not when it's not charging. `acpi` outputs 
```
Battery 0: Not charging, 99%
```
when this is the case and the widget shows 0% battery and a warning.
`acpi -a` outputs
```
Adapter 0: on-line
```
when I'm plugged in and
```
Adapter 0: off-line
```
when I'm not, so perhaps that can be helpful in finding a solution.
